<?php
use Migrations\AbstractSeed;

/**
 * JournalType1 seed.
 */
class JournalTypeSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 18,
                'type_name' => 'Employee Cost',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:43:38',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:43:38',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 0,
            ],
            [
                'id' => 19,
                'type_name' => 'Depreciation',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:45:17',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:45:17',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 0,
            ],
            [
                'id' => 20,
                'type_name' => 'Finance Cost',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:45:35',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:45:35',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 0,
            ],
            [
                'id' => 21,
                'type_name' => 'S&D Expense',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:46:17',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:46:17',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 0,
            ],
            [
                'id' => 22,
                'type_name' => 'Other Expenses',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:46:35',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:46:35',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 0,
            ],
            [
                'id' => 23,
                'type_name' => 'Other Income',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:46:52',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:46:52',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 0,
            ],
            [
                'id' => 24,
                'type_name' => 'Opening Stock',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:47:39',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:47:39',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 25,
                'type_name' => 'Sales',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:48:09',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:48:09',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 26,
                'type_name' => 'Purchase',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:48:29',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:48:29',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 27,
                'type_name' => 'Sales Return',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:48:49',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:48:49',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 28,
                'type_name' => 'Purchase Returns',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:58:27',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:58:27',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 29,
                'type_name' => 'Sales Discount',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:58:55',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:58:55',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 30,
                'type_name' => 'Purchase Rebate',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:59:23',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:59:23',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 31,
                'type_name' => 'Direct Expenses',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 14:59:48',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 14:59:48',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 1,
            ],
            [
                'id' => 32,
                'type_name' => 'Bank A/C',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:00:32',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:00:32',
                'is_credit' => 1,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 33,
                'type_name' => 'Bank Loan A/C',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:01:37',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:01:37',
                'is_credit' => 1,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 34,
                'type_name' => 'Capital',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:04',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:04',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 36,
                'type_name' => 'Movable assets',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:03:36',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:03:36',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 37,
                'type_name' => 'Fixed Assets',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:04:48',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:04:48',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 38,
                'type_name' => 'Investments',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:05:17',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:05:17',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 44,
                'type_name' => 'Sundry Debtors',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:18:32',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:18:32',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 45,
                'type_name' => 'Sundry Advance',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:19:24',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:19:24',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 46,
                'type_name' => 'Cash',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:19:24',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:19:24',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 3,
            ],
            [
                'id' => 43,
                'type_name' => 'Sundry Creditors',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:09:13',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:09:13',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 42,
                'type_name' => 'Other Borrowals',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:08:35',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:08:35',
                'is_credit' => 0,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                'id' => 35,
                'type_name' => 'Fixed Deposit',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:59',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:59',
                'is_credit' => 1,
                'is_debit' => 1,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                // 'id' => 47,
                'type_name' => 'P/L Accounts',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:59',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:59',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 4,
            ],
            [
                // 'id' => 48,
                'type_name' => 'Reserves & Surpluse',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:59',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:59',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 4,
            ],
            [
                // 'id' => 48,
                'type_name' => 'Other current assets',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:59',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:59',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                // 'id' => 48,
                'type_name' => 'Duties and Taxes',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:59',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:59',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
            [
                // 'id' => 48,
                'type_name' => 'Loans and Advances',
                'is_active' => 1,
                'created_by' => 1,
                'created_on' => '2019-09-23 15:02:59',
                'modified_by' => 1,
                'modified_on' => '2019-09-23 15:02:59',
                'is_credit' => 1,
                'is_debit' => 0,
                'journal_type_subs_exists' => 0,
                'hoa_type' => 2,
            ],
        ];

        $table = $this->table('journal_types');
        $table->insert($data)->save();
    }
}
